### ISSUE TITLE
Unable to create files with the same name at different context levels

### ISSUE THREAD

**Issue by belvedere-trading** [ConfigHubPub/ConfigHubPlatform#15]
Hey there,

Not sure if this is intended or not (whether this would be considered a bug or a feature request), but I've just noticed that we're not currently able to manage multiple files with the same name at different context levels. This is something that'll be pretty important for us in the future; our proposed workflow internally relies heavily on files as the interface via which we'll pull our configurations and we need a way for developers to be able to modify file structures for their own local development without affecting other devs (or, worse, production!).

Thanks,
Jordan

**Comment by edoarsla** [comment]
Hi Jordan.  This is a regression bug.  We already have a fix and will release as soon as all testing is complete.

Thank you,
Edin

**Comment by edoarsla** [comment]
Hi Jordan,

We've updated the tar-ball for version v1.3.6 that contains the fix for files.
For convenience, we also added a ROOT.war file, which you can use to just drop/replace existing.

https://github.com/ConfigHubPub/ConfigHubPlatform/releases/tag/v1.3.6

To patch:

1. Shut down ConfigHub server instance
2. `cd confighub-1.3.6/server/webapps`
3. rm -rf *
4. `mv <download-dir>/ROOT.war .`
5. Start ConfigHub instance `confighub-1.3.6/server/bin/startup.sh`

Thank you,
Edin

**Comment by edoarsla** [comment]
Fixed as of 1.3.6.
