### ISSUE TITLE
shutdown.sh not working properly

### ISSUE THREAD

**Issue by lemongrabber** [ConfigHubPub/ConfigHubPlatform#23]
When attempting to shutdown the confighub service using server/bin/shutdown.sh, it doesn't actually stop the process. We've had to resort from killing it on the command line.

**Comment by edoarsla** [comment]
Yea.  I find this to be the case with all Tomcat/TomEE servers.  Not sure why.  We exit cleanly (disconnect from database, etc.), but some Tomcat threads do stay up.

For this reason, we had (since v1.0) had a flag "ConfigHubEnterprise" that can be used to identify the process.  We have a wrapper script for shutdown that does:

```
sudo $TOMEE_ROOT/bin/shutdown.sh
sleep 5
sudo kill -9 $(ps auxww | grep '[C]onfigHubEnterprise' | awk '{print $2}')
```

So, we try to shutdown cleanly, and if that fails, we just kill it.

Hope this helps.

**Comment by lemongrabber** [comment]
Yeah that's good to know, I'll make sure to call the shutdown script before killing the process in order to properly close down db connections and whatnot. We will probably wrap this is a proper SystemD startup script at some point at which point we can take care of this internal to the service script
