### ISSUE TITLE
Cant adopt confighub without an opensource server

### ISSUE THREAD

**Issue by gnrlist** [ConfigHubPub/ConfigHubPlatform#32]
Do you have a plan to opensource the server side?

**Comment by edoarsla** [comment]
Yea. Sorry to hear that. We are considering open sourcing, but we're not there yet. 

Certainly we can appreciate all benefits that go with that decision, but it is a decision you make only once. We want to make sure that path is right for us.

**Comment by edoarsla** [comment]
Btw, since we're still collecting feedback, could you let us know why open source is a requirement for you?

**Comment by gnrlist** [comment]
Of course :). My company requires security vetting for all the software we use. In the case of closed source software we usually evaluate the security vetting (3rd party pen tests etc) that have already been done and how changes are handled in the future. With software we purchase there is an expectation and legal obligation for an ongoing relationship that keeps the security bar at the same level.  

If the software is free, but not open source, there is no guarantee of visibility into future bugs or speed of bug fixes. If it's open source we can do the testing/vetting and fixing ourself :)

**Comment by edoarsla** [comment]
Got it. This is great feedback - thank you very much.  Originally we had a price point and the SLA written up. But then we got cold feet and were too hungry for early adopters. Since we removed the price point we had about 200 installs, over about 4 month period. 

Our current roadmap has several components we are still working on what would be considered enterprise features with a price tag attached, as well as the SLA.

We would love to have your evaluation as well, and if you decided to move forward with the solution, we can certainly discuss the SLA - if we don't open source by then.  I assume it would have some provisions that would have associated cost for direct support access, custom features (if any), and whatever else may come up, including code escrow.

**Comment by gnrlist** [comment]
If you're looking for a good business model I'd suggest mirroring Hashicorp's. Which is essentially opensource the base functionality, keep things modular and open to plug-ability, then charge $$$$ for the remaining features that reduce operational costs and added support.
