### ISSUE TITLE
Automating upgrade db scripts

### ISSUE THREAD

**Issue by DennisHarper** [ConfigHubPub/ConfigHubPlatform#50]
It would be nice if in tarball of a new version, there is a convention such that script that contains all of the needed upgrade scripts are included. This would allow for a cleaner update path making automation easier.

**Comment by edoarsla** [comment]
Yea, we hear you, and our throughs exactly.  For a while, we've been wanting to do that, as well have a database upgrade mechanism rolled into the upgrade/downgrade process.

Its on our list, but feature development always appears to take a higher priority, but it will happen - hopefully sooner rather than later.

**Comment by samrocketman** [comment]
Refer to https://github.com/ConfigHubPub/database-migrator for ongoing work.

**Comment by edoarsla** [comment]
This is implemented in https://github.com/ConfigHubPub/Database-Manager repo, and the executable Jar is added to the v1.8 release.  We're using liquibase for DB upgrades.
