### ISSUE TITLE
Search on instance name

### ISSUE THREAD

**Issue by jmku** [ConfigHubPub/ConfigHubPlatform#53]
Currently we can either specify * or a specific instance name, but we cannot search on instance names that contain a keyword.  Can we have such a functionality?  For example, "abc*" would mean that we want all instances whose name starts with "abc".

**Comment by edoarsla** [comment]
Hi.  Where are you searching - properties, files, or within context elements - or all of the above?

Depending on the version you're running, but certainly since v1.6, if you navigate to the list of all context elements (by clicking on any name of a context-hirarchy), you can search across all context elements.  Clicking on any specific context element will also list all properties that use it.

Note:  none of the searches support regex - and characters like "*" are stripped away before the search.  In the current UI searches, results are matched as substrings among the search fields - basically as *<term>*.

**Comment by edoarsla** [comment]
jmku, does this answer your question, or do you think there's still a feature you are interested in?
