### ISSUE TITLE
Dockerfile for v1.8

### ISSUE THREAD

**Issue by krystofurr** [ConfigHubPub/ConfigHubPlatform#73]
Hi,

The Dockerfile used to create the container for ConfigHub still shows for v1.7.  To use 1.8, can someone simply update the Dockerfile to 1.8?  If not, I was just wondering a timeframe on when it would be updated?  :P

**Comment by edoarsla** [comment]
I have not released 1.8 yet because of the schema changes.  I want to switch database versioning to liquibase before the official 1.8.  Recent changes included support for Oracle database which contain changes that do need better management.  So far its all been manual, and its not sustainable going forward.

If you are starting from scratch, you can build top-of-tree and you have 1.8 - dockerized or not.

**Comment by edoarsla** [comment]
Just wanted to let you know - last night we released v1.8 (docker as well), and the new liquibase database migration tool.  Sorry for the delays!
